# Generated by Django 4.1 on 2022-08-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="con",
            name="messege",
            field=models.TextField(default="", editable=False),
        ),
    ]
