# Generated by Django 4.1 on 2022-08-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogclass',
            name='slug',
            field=models.SlugField(default=43357),
            preserve_default=False,
        ),
    ]
