# Generated by Django 4.1 on 2022-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blogclass_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryclass',
            name='slug',
            field=models.SlugField(default=3344323),
            preserve_default=False,
        ),
    ]
