# Generated by Django 4.1 on 2022-12-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='https://www.maxpixel.net/static/photo/1x/Web-404-Page-Problem-Monitor-Error-Found-1350918.png', upload_to=''),
        ),
    ]
